### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by Kiraprint** [asmpro7/QrFlow#1]
Flow Launcher version: 1.16.2
OS Version: 22631.2361
IntPtr Length: 8
x64: True

Python Path: C:\Users\kiril\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 10/08/2023 01:55:07
Exception:
QrFlow Exception: 
Websites: https://github.com/asmpro7/QrFlow
Author: Ahmed ElSaeed
Version: 1.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\kiril\AppData\Roaming\FlowLauncher\Plugins\QrFlow-1.1.0\main.py", line 12, in <module>
    import qrcode
  File "C:\Users\kiril\AppData\Roaming\FlowLauncher\Plugins\QrFlow-1.1.0\lib\qrcode\__init__.py", line 1, in <module>
    from qrcode.main import QRCode
  File "C:\Users\kiril\AppData\Roaming\FlowLauncher\Plugins\QrFlow-1.1.0\lib\qrcode\main.py", line 15, in <module>
    from typing_extensions import Literal
  File "C:\Users\kiril\AppData\Roaming\FlowLauncher\Plugins\QrFlow-1.1.0\lib\typing_extensions.py", line 1174, in <module>
    class TypeVar(typing.TypeVar, _DefaultMixin, _root=True):
TypeError: type 'typing.TypeVar' is not an acceptable base type

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\kiril\AppData\Roaming\FlowLauncher\Plugins\QrFlow-1.1.0\main.py", line 12, in <module>
    import qrcode
  File "C:\Users\kiril\AppData\Roaming\FlowLauncher\Plugins\QrFlow-1.1.0\lib\qrcode\__init__.py", line 1, in <module>
    from qrcode.main import QRCode
  File "C:\Users\kiril\AppData\Roaming\FlowLauncher\Plugins\QrFlow-1.1.0\lib\qrcode\main.py", line 15, in <module>
    from typing_extensions import Literal
  File "C:\Users\kiril\AppData\Roaming\FlowLauncher\Plugins\QrFlow-1.1.0\lib\typing_extensions.py", line 1174, in <module>
    class TypeVar(typing.TypeVar, _DefaultMixin, _root=True):
TypeError: type 'typing.TypeVar' is not an acceptable base type

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Kiraprint** [comment]
Basically, for me helped reinstall of plugin.
Btw, thank you for developing this. In some cases very helpful and fast, comparing to some online services.
